sequenceDiagram
Actor unauthenticatedUser as Unauthenticated User
Participant website as Website
Participant requestPasswordResetServlet as RequestPasswordReset Servlet
Participant userRepository as User Repository
Participant passwordResetTokenRepository as PasswordResetToken Repository
Participant emailUtility as Email Utility

unauthenticatedUser->>website: /forgot-password
website->>requestPasswordResetServlet: POST: email
requestPasswordResetServlet->>userRepository: findUserByEmail(email)
userRepository->>requestPasswordResetServlet: user

break when user is null i.e. no user for email given exists
requestPasswordResetServlet->website: show failure
end

requestPasswordResetServlet->>passwordResetTokenRepository: createPasswordResetTokenForUser(user)
passwordResetTokenRepository->>requestPasswordResetServlet: passwordResetToken

requestPasswordResetServlet->>emailUtility: sendEmail(email, resetToken)
emailUtility-->>unauthenticatedUser: email Password Reset Token with instructions

emailUtility->>website: show success
